### ISSUE TITLE
error while using code in QT Creator

### ISSUE THREAD

**Issue by akshayjain708** [teriflix/scrite#216] opened 2021-04-24 13:53 UTC
while observing the code (import scrite 1.0 and  error: Project ERROR: Unknown module(s) in QT: multimedia ) this always pops up
Is there any specific settings of files we need while running the code ?

plz help

**Comment by teriflix** [comment] 2021-04-24 14:06
Well, this is not a bug. Please start a thread on the forum. 

https://www.scrite.io/index.php/forum/forum/software-development/

Closing the ticket.

**Closed as completed by teriflix** 2021-04-24 14:06 UTC
